spring:
  rabbitmq:
    host: 192.168.199.200
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

#    listener:
#      simple:
#        acknowledge-mode: manual
#        prefetch: 10
#        concurrency: 2
#        max-concurrency: 5