spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?charset=utf8mb4&useSSL=false
    username: root
    password: 658080
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接池时建立的物理连接的数量
      initial-size: 5
      # 连接池最大数量
      max-active: 20
      # 获取连接最大等待时间
      max-wait: 60000
      # 连接池最小数量
      min-idle: 5
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: false
      # 如果启用PSCache，必须配置大于0，如果没有启动，当大于0时，poolPreparedStatements自动触发修改为true。
      # 启动PCCache后，每个连接上PSCache的数量
      max-pool-prepared-statement-per-connection-size: -1
      # 用于检测连接会否有效的sql
      validation-query: ~
      # 检测连接是否有效的超时时间
      validation-query-timeout: 1
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      #           2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 6000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 1800000
      # 监控页面相关配置
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        # ip白名单
        allow: ~
        # ip黑名单，和白名单冲突时，黑名单优先级高
        deny: ~
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall



